export default {
  screenContainer: {
    // width: "100vw",
    // height: "100vh",
    display: "flex",
    margin: "30px 100px 0px",
    // boxShadow: "1px 4px 1px 1px #888888",
    justifyContent: "center",
    flexDirection: "column",
  },
  mainTitle: {
    fontSize: 24,
    fontWeight: 500,
    display: "flex",
    justifyContent: "center",
    marginBottom: 10,
  },
  title: {
    fontSize: 20,
    fontWeight: 500,
    padding: "10px 20px",
    marginBottom: 30,
    borderBottom: "1px solid rgb(229 229 229)",
  },
  section: {
    marginTop: 20,
    boxShadow: "1px 1px 1px 2px rgb(229 229 229)",
    paddingBottom: 20,
  },
  loading: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  containerForm: {
    paddingRight: 80,
  },
  footer: {
    position: "fixed",
    bottom: 10,
    left: 0,
    paddingRight: 40,
    backgroundColor: "black",
    width: "100vw",
    height: 50,
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
};
